name: Spin up Self hosted compute

on:
  workflow_call:
    inputs:
      name:
        required: true
        description: "Droplet name"
        type: string

      image:
        required: false
        description: "Image name"
        default: ubuntu-21-10-x64
        type: string
      
      region:
        required: false
        description: "Region of Droplet"
        default: fra1
        type: string
      
      size:
        required: false
        description: "Droplet size"
        default: c-32
        type: string

    secrets:
      access-token:
        description: 'A token passed from the caller workflow'
        required: true

      do-access-token:
        description: 'An API token to access DigitalOcean with'
        required: true

jobs:
  spin-up:
    runs-on: ubuntu-latest
    steps:
    # Install Doctl
    - name: Install doctl
      uses: digitalocean/action-doctl@v2
      with:
        token: ${{ secrets.do-access-token }}

    # Template out the file for user-data
    - name: Template out file
      run: |
        cat << EOF > ./user-data
        #!/bin/bash
        
        curl -fsSL https://get.docker.com -o get-docker.sh
        sh get-docker.sh

        apt -y update
        apt -y install jq
        useradd -m gha-runner
        echo "gha-runner ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers.d/gha-runner
        export RUNNER_CFG_PAT="${{ secrets.access-token }}"
        cd /home/gha-runner
        curl -s https://raw.githubusercontent.com/actions/runner/main/scripts/create-latest-svc.sh | sudo -E -s -u gha-runner bash -s ${{ github.repository }}
        EOF

    # Create the VM
    - name: Create vm ${{ inputs.name }}
      run: doctl compute droplet create ${{ inputs.name }} --image ${{ inputs.image }} --region ${{ inputs.region }} --size ${{ inputs.size }} --wait --user-data-file ./user-data > /dev/null

    - name: Wait for VM to come online
      run: | 
        sleep 30
        for ATTEMPT in {1..10};
        do
          echo "#### Attempt $ATTEMPT ####"
          if curl -s -X GET https://api.github.com/repos/${{ github.repository }}/actions/runners -H "accept: application/json" -H "authorization: token ${{ secrets.access-token }}" | jq -er '.runners[] | select(.name == "${{ inputs.name }}") | has("status")';
          then
            exit 0
          fi
          sleep 30
        done
        exit 1