name: Tear down Self hosted compute

on:
  workflow_call:
    inputs:
      name:
        required: true
        description: "Droplet name"
        type: string

    secrets:
      access-token:
        description: 'A token passed from the caller workflow'
        required: true

      do-access-token:
        description: 'An API token to access DigitalOcean with'
        required: true

jobs:
  spin-up:
    runs-on: ubuntu-latest
    steps:
    # Install Doctl
    - name: Install doctl
      uses: digitalocean/action-doctl@v2
      with:
        token: ${{ secrets.do-access-token }}

    # Create the VM
    - name: Delete vm ${{ inputs.name }}
      run: doctl compute droplet delete ${{ inputs.name }} -f

    - name: Delete the runner
      run: | 
        RUNNER_ID=$(curl -s -X GET https://api.github.com/repos/${{ github.repository }}/actions/runners -H "accept: application/json" -H "authorization: token ${{ secrets.access-token }}" | jq -er '.runners[] | select(.name == "${{ inputs.name }}").id')
        curl -s -X DELETE https://api.github.com/repos/${{ github.repository }}/actions/runners/$RUNNER_ID -H "accept: application/json" -H "authorization: token ${{ secrets.access-token }}"
